name: CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn

      - name: Run ESLint
        run: node_modules/.bin/eslint . --ext .js
